import { Modal, View, Text, Pressable } from "react-native";
import { router } from "expo-router"
type Termsandcoprops = {
  visible: boolean;
  onCancel: () => void;
  onConfirm: () => void;
};

export default function Termsandco({
  visible,
  onCancel,
  onConfirm,
}: Termsandcoprops) {
  return (
    <Modal
      visible={visible}
      transparent
      animationType="fade"
      statusBarTranslucent
    >
      {/* Overlay */}
      <View className="flex-1 items-center justify-center bg-black/60">
        {/* Card */}
        <View className="w-[85%] rounded-2xl bg-white p-6">
          <Text className="text-lg font-semibold text-gray-900">
            Terms and Condition
          </Text>

          <Text className="mt-2 text-sm text-gray-500">
            By using ChatMeAI, you agree to the following:

           1. ChatMeAI provides AI-generated responses for informational and entertainment purposes only. {"\n"}

           2. Responses may be inaccurate, incomplete, or outdated. Always verify important information. {"\n"}

           3. ChatMeAI does not provide professional advice (medical, legal, financial, or otherwise). {"\n"}

           4. You are responsible for how you use the responses generated by the app. {"\n"}

           5. Do not use ChatMeAI for illegal, harmful, abusive, or misleading activities. {"\n"}

           6. We may update or discontinue features at any time without notice. {"\n"}

            By continuing to use the app, you agree to these terms. {"\n"}
          </Text>

          {/* Buttons */}
          <View className="mt-6 flex-row justify-end space-x-3 gap-4">
            <Pressable
              onPress={onCancel}
              className="rounded-xl bg-red-600 px-5 py-2"
            >
              <Text className="text-white font-medium">
                Cancel
              </Text>
            </Pressable>

            <Pressable
              onPress={onConfirm}
              className="rounded-xl bg-yellow-400 px-5 py-2"
            >
              <Text className="text-black font-medium">
                Agree
              </Text>
            </Pressable>
          </View>
        </View>
      </View>
    </Modal>
  );
}
